#Control how many question per round, if nr is set higher than amount of quetions in chosen subject it will not run as intended(currently 4)
questionsPerRound=2

#Control how many rounds per game
roundsPerGame=2

#Control how many choices of subject is presented, if nr is higher that amount of subject it will not run as intended(currently 4)
subjectsPerChoice=3